"""Public Commander Gym research/evaluation interfaces."""

from .argentum import (
    ArgentumCanonicalDecision,
    ArgentumCanonicalError,
    StaleArgentumDecisionError,
)
from .argentum_client import (
    ArgentumClientConfigurationError,
    ArgentumClientError,
    ArgentumConnectionError,
    ArgentumDeliveryUnknownError,
    ArgentumGymClient,
    ArgentumRemoteError,
)
from .benchmark_runner import (
    BENCHMARK_REPORT_VERSION,
    BenchmarkInput,
    BenchmarkPilot,
    CallablePilot,
    PilotDecision,
    benchmark_input_for_case,
    first_legal_pilot,
    run_benchmark,
)
from .dataset_export import (
    DATASET_EXPORT_SCHEMA_VERSION,
    DatasetExportError,
    build_run_dataset_rows,
    write_run_dataset_jsonl,
)
from .deck_package import (
    DECK_PACKAGE_SCHEMA_VERSION,
    ArtifactRef,
    DeckPackage,
    DeckPackageError,
    validate_commander_package,
)
from .deck_source_fetch import DeckSourceFetchError, fetch_archidekt_snapshot
from .deck_sources import (
    DECK_SOURCE_SCHEMA_VERSION,
    DeckSourceEntry,
    DeckSourceError,
    DeckSourceSnapshot,
    normalize_archidekt_snapshot,
)
from .experiment import (
    EXPERIMENT_ARTIFACT_VERSION,
    EXPERIMENT_PLAN_SCHEMA_VERSION,
    ExperimentError,
    ExperimentPlan,
    ExperimentResult,
    ExperimentRunSpec,
    run_experiment,
    write_experiment_artifact,
)
from .openai_responses_pilot import OpenAIResponsesPilot, OpenAIResponsesPilotError
from .orchestration import (
    ArgentumOrchestrator,
    CreationReconciliation,
    EnvironmentReconciliation,
    OrchestrationBackend,
    OrchestrationCompatibilityError,
    OrchestrationError,
    OrchestrationInspection,
    OrchestrationReconciliationError,
    ServerIdentity,
)
from .pilot import (
    ArtificialPlayer,
    ArgentumActionChoice,
    ArgentumDecisionChoice,
    PilotChoice,
    PilotContractError,
    choose_for_observation,
    validate_pilot_choice,
)
from .pilot_records import (
    PilotRecordContext,
    PilotRecordError,
    decision_record_from_execution_trace,
    structured_decision_record_from_execution_trace,
)
from .pilot_routing import (
    CertifiedMechanicalHandler,
    ForcedParameterlessChoiceHandler,
    RoutingPilot,
)
from .pilot_session import (
    PILOT_SESSION_ARTIFACT_VERSION,
    PilotSeat,
    PilotSessionError,
    PilotSessionResult,
    run_four_seat_pilot_session,
    write_pilot_session_artifact,
)
from .records import (
    ActionRecord,
    DecisionRecord,
    PilotProvenance,
    RecordValidationError,
    StructuredDecisionRecord,
)
from .run_records import (
    RUN_RECORD_SCHEMA_VERSION,
    RUN_STATUS_COMPLETED,
    RUN_STATUS_FAILED,
    RUN_STATUS_STOPPED,
    EngineProvenance,
    RunParticipant,
    RunRecord,
    RunTermination,
)
from .sparse_features import (
    DEFAULT_FEATURE_SPACE,
    FEATURE_SCHEMA_VERSION,
    SparseDecisionFeatures,
    encode_decision_record,
    policy_family_for_decision_type,
)

__all__ = [
    "ActionRecord",
    "ArtificialPlayer",
    "ArgentumActionChoice",
    "ArgentumCanonicalDecision",
    "ArgentumCanonicalError",
    "ArgentumClientConfigurationError",
    "ArgentumClientError",
    "ArgentumConnectionError",
    "ArgentumDecisionChoice",
    "ArgentumDeliveryUnknownError",
    "ArgentumGymClient",
    "ArgentumOrchestrator",
    "ArgentumRemoteError",
    "ArtifactRef",
    "BENCHMARK_REPORT_VERSION",
    "BenchmarkInput",
    "BenchmarkPilot",
    "CallablePilot",
    "CertifiedMechanicalHandler",
    "CreationReconciliation",
    "DATASET_EXPORT_SCHEMA_VERSION",
    "DEFAULT_FEATURE_SPACE",
    "DECK_PACKAGE_SCHEMA_VERSION",
    "DECK_SOURCE_SCHEMA_VERSION",
    "DatasetExportError",
    "DeckPackage",
    "DeckPackageError",
    "DeckSourceEntry",
    "DeckSourceError",
    "DeckSourceFetchError",
    "DeckSourceSnapshot",
    "DecisionRecord",
    "EXPERIMENT_ARTIFACT_VERSION",
    "EXPERIMENT_PLAN_SCHEMA_VERSION",
    "EngineProvenance",
    "EnvironmentReconciliation",
    "ExperimentError",
    "ExperimentPlan",
    "ExperimentResult",
    "ExperimentRunSpec",
    "FEATURE_SCHEMA_VERSION",
    "ForcedParameterlessChoiceHandler",
    "OpenAIResponsesPilot",
    "OpenAIResponsesPilotError",
    "OrchestrationBackend",
    "OrchestrationCompatibilityError",
    "OrchestrationError",
    "OrchestrationInspection",
    "OrchestrationReconciliationError",
    "PilotChoice",
    "PilotContractError",
    "PilotDecision",
    "PilotProvenance",
    "PilotRecordContext",
    "PilotRecordError",
    "PILOT_SESSION_ARTIFACT_VERSION",
    "PilotSeat",
    "PilotSessionError",
    "PilotSessionResult",
    "RUN_RECORD_SCHEMA_VERSION",
    "RUN_STATUS_COMPLETED",
    "RUN_STATUS_FAILED",
    "RUN_STATUS_STOPPED",
    "RecordValidationError",
    "RoutingPilot",
    "RunParticipant",
    "RunRecord",
    "RunTermination",
    "ServerIdentity",
    "SparseDecisionFeatures",
    "StructuredDecisionRecord",
    "StaleArgentumDecisionError",
    "benchmark_input_for_case",
    "build_run_dataset_rows",
    "choose_for_observation",
    "decision_record_from_execution_trace",
    "structured_decision_record_from_execution_trace",
    "encode_decision_record",
    "fetch_archidekt_snapshot",
    "first_legal_pilot",
    "normalize_archidekt_snapshot",
    "policy_family_for_decision_type",
    "run_benchmark",
    "run_experiment",
    "run_four_seat_pilot_session",
    "validate_commander_package",
    "validate_pilot_choice",
    "write_experiment_artifact",
    "write_pilot_session_artifact",
    "write_run_dataset_jsonl",
]
