"""Audit exact offline GameServer HTTP capture and build a small private model-input corpus.

No provider is contacted. All model input strings are generated by the production Gym
seat adapter and Responses observation projection, including canonical knownDeck.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess

from commander_gym.binding_catalog import load_binding_catalog
from commander_gym.game_server_bindings import GameServerBindingRegistry
from commander_gym.observation_projection import compact_seat_observation, expand_seat_observation
from commander_gym.openai_responses_pilot import _without_live_routing
from scripts.run_paired_view_screen import _captured_request


class _CapturedObservation(Exception):
    def __init__(self, observation):
        self.observation = observation


class _NeverRunPilot:
    name = "offline-audit-only"
    version = "1"

    def choose(self, observation):
        raise _CapturedObservation(dict(observation))


def _bound_observation(adapter, observation):
    try:
        adapter._pilot.choose(observation)
    except _CapturedObservation as captured:
        bound = captured.observation
    else:
        raise AssertionError("audit Pilot unexpectedly returned a choice")
    assert isinstance(bound.get("deckKnowledge"), str) and bound["deckKnowledge"].strip()
    return bound


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _count_exact(value, ids: set[str]) -> int:
    if isinstance(value, dict):
        return sum(int(isinstance(k, str) and k in ids) + _count_exact(v, ids)
                   for k, v in value.items())
    if isinstance(value, list):
        return sum(_count_exact(v, ids) for v in value)
    return int(isinstance(value, str) and value in ids)


def _assert_library_visibility(state, viewer: str) -> tuple[set[str], set[str]]:
    """Use native zone visibility, not the presence of a named card, as authority."""
    opaque: set[str] = set()
    visible: set[str] = set()
    for zone in state["zones"]:
        if zone["zoneId"]["zoneType"] != "Library":
            continue
        own = zone["zoneId"]["ownerId"] == viewer
        for card_id in zone["cardIds"]:
            if card_id.startswith("client-hidden-library-slot:"):
                assert card_id not in state["cards"]
                opaque.add(card_id)
            else:
                assert own and zone["isVisible"] is True, "unrevealed library identity escaped"
                assert card_id in state["cards"]
                assert state["cards"][card_id]["name"] != "Face-down card"
                visible.add(card_id)
    return opaque, visible


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--capture-dir", type=Path, required=True)
    parser.add_argument("--instance-root", type=Path, required=True)
    parser.add_argument("--catalog", type=Path, required=True)
    parser.add_argument("--corpus-dir", type=Path, required=True)
    parser.add_argument("--max-selected", type=int, default=8)
    args = parser.parse_args()
    if args.max_selected <= 0:
        parser.error("max-selected must be positive")
    root = args.instance_root.resolve(strict=True)
    loaded = load_binding_catalog(args.catalog, instance_root=root,
                                  pilot_factory=lambda _pilot, _binding: _NeverRunPilot())
    registry = GameServerBindingRegistry(loaded.resolver, loaded.binding_ids)
    capture = args.capture_dir.resolve(strict=True)
    output = args.corpus_dir.resolve()
    os.umask(0o077)
    output.mkdir(mode=0o700, parents=True, exist_ok=True)
    if output.stat().st_mode & 0o077:
        raise RuntimeError("corpus directory must be private")
    files = sorted(capture.glob("*.json"), key=lambda p: (p.stat().st_mtime_ns, p.name))
    if not files:
        raise RuntimeError("no native HTTP callback bodies found")
    summary_path = capture.parent / "summary.json"
    summary = json.loads(summary_path.read_text())
    if summary.get("providerCalls") != 0 or summary.get("httpCallbacks") != len(files):
        raise RuntimeError("capture summary and settled HTTP callback set disagree")
    rows = []
    candidates = []
    for source in files:
        raw = source.read_bytes()
        body = json.loads(raw)
        row = {"httpSha256": _sha(raw), "httpBytes": len(raw),
               "callback": "action" if "state" in body else "mulligan" if "mulligan" in body else "bottom"}
        if "state" not in body:
            rows.append(row)
            continue
        state = body["state"]
        viewer = state["viewingPlayerId"]
        assert viewer == body["playerId"]
        profile = body["profileId"]
        adapter = registry.create_seat(viewer, profile)
        observation = adapter._observation(state, body["legalActions"],
                                           body["pendingDecision"], body["recentGameLog"])
        assert viewer == observation["agentToAct"] == observation["perspectivePlayerId"]
        assert observation["knownDeck"]["cards"]
        observation = _bound_observation(adapter, observation)
        opponents = {p["playerId"] for p in state["players"] if p["playerId"] != viewer}
        hands = [z for z in state["zones"] if z["zoneId"]["ownerId"] in opponents and z["zoneId"]["zoneType"] == "Hand"]
        libraries = [z for z in state["zones"] if z["zoneId"]["ownerId"] in opponents and z["zoneId"]["zoneType"] == "Library"]
        all_libraries = [z for z in state["zones"] if z["zoneId"]["zoneType"] == "Library"]
        assert hands and libraries and all_libraries
        assert all(not z["isVisible"] and not z["cardIds"] for z in hands)
        assert all(len(z["cardIds"]) == z["size"] for z in all_libraries)
        opaque, visible = _assert_library_visibility(state, viewer)
        for key in ("legalActions", "pendingDecision", "recentGameLog"):
            assert _count_exact(body[key], opaque) == 0
        for key in ("cards", "players", "deck", "gameLog", "combat", "activeYields"):
            assert _count_exact(state.get(key), opaque) == 0
        assert not any(card.get("zone", {}).get("zoneType") == "Hand" and
                       card.get("zone", {}).get("ownerId") in opponents for card in state["cards"].values())
        full = _without_live_routing(observation)
        compact = compact_seat_observation(full)
        assert expand_seat_observation(compact) == full
        for payload in (full, compact):
            assert _count_exact(payload, opaque) == len(opaque)
        requests = {
            "full": _captured_request(observation, False),
            "compact": _captured_request(observation, True),
        }
        for label, payload in (("full", full), ("compact", compact)):
            expected_input = "Return one JSON object for this observation:\n" + json.dumps(
                payload, sort_keys=True, separators=(",", ":"),
            )
            assert requests[label]["input"] == expected_input
        pending = body["pendingDecision"]
        row.update({"profileId": profile, "viewerId": viewer, "turn": state["turnNumber"],
                    "step": state["currentStep"], "opponentHandSizes": [z["size"] for z in hands],
                    "opponentLibrarySizes": [z["size"] for z in libraries],
                    "opaqueLibrarySlots": len(opaque), "visibleLibraryIds": len(visible),
                    "visibleOwnLibraryIds": sum(card_id in visible for z in all_libraries
                                                if z["zoneId"]["ownerId"] == viewer for card_id in z["cardIds"]),
                    "visibleOpponentLibraryIds": sum(card_id in visible for z in libraries for card_id in z["cardIds"]),
                    "structuredDecision": pending.get("type") if isinstance(pending, dict) else None,
                    "responseSpecPresent": bool(isinstance(pending, dict) and pending.get("responseSpec")),
                    "combatPresent": state["combat"] is not None,
                    "faceDownCardCount": sum(card.get("isFaceDown") is True for card in state["cards"].values()),
                    "fullCompactRoundtrip": True})
        rows.append(row)
        candidates.append((row, raw, full, compact, requests))
    # Pick earliest per seat plus every new observed category, then balance seats/turns.
    selected = []
    seen = set()
    known_library_seen = set()
    for candidate in candidates:
        row = candidate[0]
        categories = {("seat", row["profileId"])}
        if row["structuredDecision"]:
            categories.add(("decision", row["structuredDecision"]))
        if row["combatPresent"]:
            categories.add(("combat", True))
        if row["visibleLibraryIds"]:
            categories.add(("library-reveal", True))
        if row["visibleOwnLibraryIds"]:
            known_library_seen.add(row["profileId"])
        elif row["profileId"] in known_library_seen:
            categories.add(("library-reconcealed", row["profileId"]))
        if row["faceDownCardCount"]:
            categories.add(("face-down", True))
        if categories - seen and len(selected) < args.max_selected:
            selected.append(candidate)
            seen.update(categories)
    while len(selected) < args.max_selected:
        remaining = [candidate for candidate in candidates
                     if candidate not in selected and candidate[0]["turn"] <= 12]
        if not remaining:
            break
        def balance_key(candidate):
            row = candidate[0]
            same_seat = [item[0] for item in selected if item[0]["profileId"] == row["profileId"]]
            return (len(same_seat), row["turn"] in {item["turn"] for item in same_seat},
                    row["turn"], candidates.index(candidate))
        selected.append(min(remaining, key=balance_key))
    reconcealment = []
    for index, (prior_row, prior_raw, _, _, _) in enumerate(candidates):
        prior = json.loads(prior_raw)
        prior_visible = {
            card_id for zone in prior["state"]["zones"]
            if zone["zoneId"]["ownerId"] == prior["playerId"] and zone["zoneId"]["zoneType"] == "Library"
            for card_id in zone["cardIds"]
            if not card_id.startswith("client-hidden-library-slot:")
        }
        if not prior_visible:
            continue
        for later_row, later_raw, _, _, _ in candidates[index + 1:]:
            later = json.loads(later_raw)
            if later["playerId"] != prior["playerId"]:
                continue
            later_slots = {
                card_id for zone in later["state"]["zones"]
                if zone["zoneId"]["ownerId"] == prior["playerId"] and zone["zoneId"]["zoneType"] == "Library"
                for card_id in zone["cardIds"]
            }
            if later_row["visibleOwnLibraryIds"] == 0:
                assert not prior_visible & later_slots
                reconcealment.append({"revealedHttpSha256": prior_row["httpSha256"],
                                      "laterHttpSha256": later_row["httpSha256"],
                                      "previouslyKnownIds": len(prior_visible),
                                      "idsLinkedToLaterLibrarySlots": 0})
            break
    assert reconcealment and any(row["previouslyKnownIds"] > 0 for row in reconcealment)
    assert {row["structuredDecision"] for row in rows if row.get("structuredDecision")} >= {
        "SelectCardsDecision", "YesNoDecision",
    }
    assert any(row.get("combatPresent") for row in rows)
    assert any(row.get("visibleOwnLibraryIds", 0) > 0 for row in rows)
    assert len(selected) == args.max_selected
    assert sorted(sum(item[0]["profileId"] == profile for item in selected)
                  for profile in summary["profiles"]) == [args.max_selected // 2] * 2
    selected_meta = []
    for index, (row, raw, full, compact, requests) in enumerate(selected):
        stem = f"sample-{index:02d}"
        (output / f"{stem}-http.json").write_bytes(raw)
        hashes = {"http": _sha(raw)}
        for label, payload in (("full", full), ("compact", compact)):
            text = "Return one JSON object for this observation:\n" + json.dumps(payload, sort_keys=True, separators=(",", ":"))
            data = text.encode()
            (output / f"{stem}-{label}-input.txt").write_bytes(data)
            hashes[label] = _sha(data)
            request_bytes = json.dumps(requests[label], sort_keys=True, separators=(",", ":")).encode()
            (output / f"{stem}-{label}-request.json").write_bytes(request_bytes)
            hashes[label + "Request"] = _sha(request_bytes)
        selected_meta.append({"index": index, "sourceHttpSha256": row["httpSha256"],
                              "turn": row["turn"], "profileId": row["profileId"],
                              "structuredDecision": row["structuredDecision"],
                              "combatPresent": row["combatPresent"], "hashes": hashes})
    audit = {"evidenceClass": "actual normal GameServer HTTP callbacks, canonical Binding deck metadata and production Gym model input projection; zero provider dispatch",
             "engineCommit": summary["engineCommit"], "captureGymCommit": summary["gymCommit"],
             "auditGymCommit": subprocess.check_output(
                 ["git", "rev-parse", "HEAD"], cwd=Path(__file__).resolve().parents[1], text=True,
             ).strip(),
             "catalogSha256": _sha(args.catalog.read_bytes()),
             "captureSummarySha256": _sha(summary_path.read_bytes()),
             "profiles": summary["profiles"], "stopReason": summary["stopReason"],
             "capturedCallbacks": len(files), "actionCallbacks": len(candidates),
             "sourceSetSha256": _sha("\n".join(sorted(row["httpSha256"] for row in rows)).encode()),
             "rows": rows, "selected": selected_meta,
             "libraryReconcealment": reconcealment, "paidCalls": 0,
             "limit": "Scripted fixture Pilot, not canonical foundation Pilot strategy. Full and compact request objects, including Binding DeckKnowledge and request-local schema, were constructed offline by the production formatter; no provider request was sent."}
    (output / "corpus-audit.json").write_text(json.dumps(audit, indent=2) + "\n")
    print(json.dumps({"callbacks": len(files), "actions": len(candidates),
                      "selected": len(selected),
                      "structured": sum(bool(r.get("structuredDecision")) for r in rows),
                      "combat": sum(bool(r.get("combatPresent")) for r in rows),
                      "paidCalls": 0}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
